
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=qwerty
      - REDIS_USER=redi
      - REDIS_PORT=6379
      - REDIS_DATABASES=2
    volumes:
      - redis_data:/data
    restart: always

  bot:
    image: sawcka/altspu_schedule_bot:latest
    build: .
    environment:
      - token=****************************
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Novosibirsk
    restart: always

volumes:
  redis_data:
